using Microsoft.EntityFrameworkCore;

namespace {ProjectName}.Data;

/// <summary>
/// Main EF Core DbContext for {ProjectName}.
/// Generated by AICASE – add entity DbSets and Fluent API configurations here.
/// </summary>
public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    // ─── DbSets ───────────────────────────────────────────────────────────────
    // AICASE_DBSETS_PLACEHOLDER
    // Example:
    // public DbSet<Cliente> Clientes { get; set; }
    // public DbSet<Producto> Productos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Apply all IEntityTypeConfiguration<T> classes in this assembly
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(ApplicationDbContext).Assembly);

        // Global query filters, value converters, etc. can be added here
        // AICASE_MODEL_BUILDER_PLACEHOLDER
    }

    /// <summary>
    /// Override SaveChanges to handle audit fields (CreatedAt, UpdatedAt).
    /// </summary>
    public override int SaveChanges()
    {
        UpdateAuditFields();
        return base.SaveChanges();
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        UpdateAuditFields();
        return base.SaveChangesAsync(cancellationToken);
    }

    private void UpdateAuditFields()
    {
        var entries = ChangeTracker.Entries()
            .Where(e => e.State == EntityState.Added || e.State == EntityState.Modified);

        foreach (var entry in entries)
        {
            if (entry.State == EntityState.Added && entry.Properties.Any(p => p.Metadata.Name == "FechaCreacion"))
                entry.Property("FechaCreacion").CurrentValue = DateTime.UtcNow;

            if (entry.Properties.Any(p => p.Metadata.Name == "FechaUltimaActualizacion"))
                entry.Property("FechaUltimaActualizacion").CurrentValue = DateTime.UtcNow;
        }
    }
}
